/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function HepatitisCell(props) {
  const { nodes, materials } = useGLTF('/models-3d/Hepatitis/HepatitisCell.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hepatitis.geometry}
        material={materials.Hepatitis}
      />
    </group>
  )
}

useGLTF.preload('/models-3d/Hepatitis/HepatitisCell.glb')