/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei' 
import { useFrame } from '@react-three/fiber'


export default function Model({animate = false, ...props}) {
  const groupRef = useRef()  
  const { nodes, materials } = useGLTF('/models-3d/Hepatitis/SyringeVial.glb')
  
  useFrame(() => {
      if (animate && groupRef.current) {
        groupRef.current.rotation.y += 0.05
      }
    })
  
  return (
    <group ref={groupRef} {...props} dispose={null}>
      
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeshBarrelSyringe001.geometry}
          material={materials.BarrelSyringe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeshBarrelSyringe001_1.geometry}
          material={materials.BarrelSyringeTexture}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeshSyringePlunger005.geometry}
          material={materials.PlungerSyringe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeshSyringePlunger005_1.geometry}
          material={materials.RubberStopperSyringe}
        />
      
      
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeshSyringeTip006.geometry}
          material={materials.TipSyringe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MeshSyringeTip006_1.geometry}
          material={materials.ShaftSyringe}
        />
      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.VialSyringe.geometry}
        material={materials.Vial}
      />
    </group>
  )
}
useGLTF.preload('/SyringeVial.glb')


